import { useState } from 'react';
import ImageCropper from './ImageCropper';
import { supabase } from '../supabaseClient';
import { useAuth } from '../components/AuthProvider';
import {
  Box,
  Paper,
  Stack,
  Button,
  FormControl,
  FormHelperText,
  CircularProgress,
  TextField,
  Autocomplete,
} from '@mui/material';





interface PhotoUploadProps {
  onUpload?: () => void;
  questId?: string;
  onCancel?: () => void;
}

import { Checkbox, FormControlLabel } from '@mui/material';

const PhotoUpload = ({ onUpload, questId, onCancel }: PhotoUploadProps) => {
  const { user } = useAuth();
  // const [speciesList, setSpeciesList] = useState<string[]>([]);
  const [speciesId, setSpeciesId] = useState<string>('');
  const [file, setFile] = useState<File | null>(null);
  // Privacy state removed
  // For thumbnail generation
  const [setAsTop, setSetAsTop] = useState(false);
  async function createThumbnail(blob: Blob, size = 360): Promise<Blob> {
    // Create an offscreen image and canvas
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const image = new window.Image();
      image.onload = () => resolve(image);
      image.onerror = reject;
      image.src = URL.createObjectURL(blob);
    });
    const canvas = document.createElement('canvas');
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('No 2d context');
    ctx.drawImage(img, 0, 0, size, size);
    return new Promise((resolve, reject) => {
      canvas.toBlob(b => b ? resolve(b) : reject(new Error('Failed to create thumbnail')), 'image/jpeg', 0.92);
    });
  }
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [showCropper, setShowCropper] = useState(false);
  const [croppedBlob, setCroppedBlob] = useState<Blob | null>(null);


  // Hardcoded species list for My Uploads page
  const HARDCODED_SPECIES = [
    "Abert's Towhee",
    "Acadian Flycatcher",
    "Acorn Woodpecker",
    "Adelaide's Warbler",
    "African Collared-Dove",
    "Agami Heron",
    "Ainley's Storm-Petrel",
    "Alder Flycatcher",
    "Aleutian Tern",
    "Allen's Hummingbird",
    "Alpine Swift",
    "Altamira Oriole",
    "Altamira Yellowthroat",
    "Amazilia Hummingbird",
    "Amazon Kingfisher",
    "American Avocet",
    "American Barn Owl",
    "American Bittern",
    "American Black Duck",
    "American Coot",
    "American Crow",
    "American Dipper",
    "American Flamingo",
    "American Golden-Plover",
    "American Goldfinch",
    "American Goshawk",
    "American Herring Gull",
    "American Kestrel",
    "American Oystercatcher",
    "American Pipit",
    "American Pygmy Kingfisher",
    "American Redstart",
    "American Robin",
    "American Three-toed Woodpecker",
    "American Tree Sparrow",
    "American White Pelican",
    "American Wigeon",
    "American Woodcock",
    "Amethyst-throated Mountain-gem",
    "Amur Stonechat",
    "Ancient Murrelet",
    "Anhinga",
    "Anna's Hummingbird",
    "Antillean Crested Hummingbird",
    "Antillean Nighthawk",
    "Antillean Palm Swift",
    "Antillean Piculet",
    "Antillean Siskin",
    "Antipodean Albatross",
    "Aplomado Falcon",
    "Arctic Loon",
    "Arctic Tern",
    "Arctic Warbler",
    "Arizona Woodpecker",
    "Arrowhead Warbler",
    "Ash-throated Flycatcher",
    "Ashy Storm-Petrel",
    "Ashy-faced Owl",
    "Ashy-throated Chlorospingus",
    "Asian Brown Flycatcher",
    "Asian Rosy-Finch",
    "Atitlan Grebe",
    "Atlantic Puffin",
    "Atlantic Yellow-nosed Albatross",
    "Audouin's Gull",
    "Audubon's Oriole",
    "Aztec Rail",
    "Aztec Thrush",
    "Azure Gallinule",
    "Azure-crowned Hummingbird",
    "Azure-hooded Jay",
    "Azure-rumped Tanager",
    "Bachman's Sparrow",
    "Bachman's Warbler",
    "Bahama Mockingbird",
    "Bahama Nuthatch",
    "Bahama Oriole",
    "Bahama Swallow",
    "Bahama Warbler",
    "Bahama Woodstar",
    "Bahama Yellowthroat",
    "Baikal Teal",
    "Baillon's Crake",
    "Baird's Junco",
    "Baird's Sandpiper",
    "Baird's Sparrow",
    "Baird's Trogon",
    "Bald Eagle",
    "Balsas Screech-Owl",
    "Baltimore Oriole",
    "Bananaquit",
    "Band-backed Wren",
    "Band-rumped Storm-Petrel",
    "Band-rumped Swift",
    "Band-tailed Barbthroat",
    "Band-tailed Pigeon",
    "Banded Quail",
    "Banded Wren",
    "Bank Swallow",
    "Bar-tailed Godwit",
    "Bar-winged Oriole",
    "Barbados Bullfinch",
    "Barbuda Warbler",
    "Bare-crowned Antbird",
    "Bare-faced Ibis",
    "Bare-legged Owl",
    "Bare-necked Umbrellabird",
    "Bare-shanked Screech-Owl",
    "Bare-throated Tiger-Heron",
    "Barn Swallow",
    "Barnacle Goose",
    "Barolo Shearwater",
    "Barred Antshrike",
    "Barred Becard",
    "Barred Forest-Falcon",
    "Barred Hawk",
    "Barred Owl",
    "Barred Parakeet",
    "Barred Puffbird",
    "Barrow's Goldeneye",
    "Bat Falcon",
    "Baudo Guan",
    "Bay Wren",
    "Bay-breasted Cuckoo",
    "Bay-breasted Warbler",
    "Bay-headed Tanager",
    "Bearded Screech-Owl",
    "Bearded Wood-Partridge",
    "Beautiful Hummingbird",
    "Beautiful Treerunner",
    "Bee Hummingbird",
    "Belcher's Gull",
    "Belding's Yellowthroat",
    "Bell's Sparrow",
    "Bell's Vireo",
    "Belted Flycatcher",
    "Belted Kingfisher",
    "Bendire's Thrasher",
    "Bermuda Petrel",
    "Berylline Hummingbird",
    "Bewick's Wren",
    "Bicknell's Thrush",
    "Bicolored Antbird",
    "Bicolored Hawk",
    "Bicolored Wren",
    "Black Antshrike",
    "Black Catbird",
    "Black Francolin",
    "Black Guan",
    "Black Guillemot",
    "Black Hawk-Eagle",
    "Black Kite",
    "Black Noddy",
    "Black Oropendola",
    "Black Oystercatcher",
    "Black Phoebe",
    "Black Rail",
    "Black Rosy-Finch",
    "Black Scoter",
    "Black Skimmer",
    "Black Storm-Petrel",
    "Black Swift",
    "Black Tern",
    "Black Thrush",
    "Black Turnstone",
    "Black Vulture",
    "Black-and-white Becard",
    "Black-and-white Hawk-Eagle",
    "Black-and-white Owl",
    "Black-and-white Warbler",
    "Black-and-yellow Silky-flycatcher",
    "Black-and-yellow Tanager",
    "Black-backed Oriole",
    "Black-backed Woodpecker",
    "Black-banded Woodcreeper",
    "Black-bellied Hummingbird",
    "Black-bellied Plover",
    "Black-bellied Storm-Petrel",
    "Black-bellied Whistling-Duck",
    "Black-bellied Wren",
    "Black-billed Amazon",
    "Black-billed Cuckoo",
    "Black-billed Flycatcher",
    "Black-billed Magpie",
    "Black-billed Nightingale-Thrush",
    "Black-billed Streamertail",
    "Black-breasted Puffbird",
    "Black-breasted Wood-Quail",
    "Black-browed Albatross",
    "Black-capped Chickadee",
    "Black-capped Donacobius",
    "Black-capped Flycatcher",
    "Black-capped Gnatcatcher",
    "Black-capped Petrel",
    "Black-capped Pygmy-Tyrant",
    "Black-capped Siskin",
    "Black-capped Swallow",
    "Black-capped Vireo",
    "Black-cheeked Ant-Tanager",
    "Black-cheeked Warbler",
    "Black-cheeked Woodpecker",
    "Black-chested Jay",
    "Black-chested Sparrow",
    "Black-chinned Hummingbird",
    "Black-chinned Sparrow",
    "Black-collared Hawk",
    "Black-cowled Oriole",
    "Black-crested Coquette",
    "Black-crested Titmouse",
    "Black-crowned Antpitta",
    "Black-crowned Antshrike",
    "Black-crowned Night Heron",
    "Black-crowned Palm-Tanager",
    "Black-crowned Tityra",
    "Black-eared Wood-Quail",
    "Black-faced Antthrush",
    "Black-faced Grassquit",
    "Black-faced Grosbeak",
    "Black-faced Solitaire",
    "Black-faced Tanager",
    "Black-footed Albatross",
    "Black-headed Antthrush",
    "Black-headed Brushfinch",
    "Black-headed Grosbeak",
    "Black-headed Gull",
    "Black-headed Nightingale-Thrush",
    "Black-headed Saltator",
    "Black-headed Siskin",
    "Black-headed Tody-Flycatcher",
    "Black-headed Trogon",
    "Black-hooded Antshrike",
    "Black-legged Kittiwake",
    "Black-necked Stilt",
    "Black-polled Yellowthroat",
    "Black-rumped Waxbill",
    "Black-striped Sparrow",
    "Black-striped Woodcreeper",
    "Black-tailed Flycatcher",
    "Black-tailed Gnatcatcher",
    "Black-tailed Godwit",
    "Black-tailed Gull",
    "Black-tailed Trogon",
    "Black-thighed Grosbeak",
    "Black-throated Blue Warbler",
    "Black-throated Bobwhite",
    "Black-throated Gray Warbler",
    "Black-throated Green Warbler",
    "Black-throated Jay",
    "Black-throated Magpie-Jay",
    "Black-throated Mango",
    "Black-throated Shrike-Tanager",
    "Black-throated Sparrow",
    "Black-throated Wren",
    "Black-tipped Cotinga",
    "Black-vented Oriole",
    "Black-vented Shearwater",
    "Black-whiskered Vireo",
    "Black-winged Stilt",
    "Blackburnian Warbler",
    "Blackpoll Warbler",
    "Blue Bunting",
    "Blue Cotinga",
    "Blue Dacnis",
    "Blue Grosbeak",
    "Blue Ground Dove",
    "Blue Jay",
    "Blue Mockingbird",
    "Blue Mountain Vireo",
    "Blue Rock-Thrush",
    "Blue Seedeater",
    "Blue-and-gold Tanager",
    "Blue-and-white Mockingbird",
    "Blue-and-white Swallow",
    "Blue-and-yellow Macaw",
    "Blue-black Grassquit",
    "Blue-black Grosbeak",
    "Blue-capped Hummingbird",
    "Blue-capped Motmot",
    "Blue-chested Hummingbird",
    "Blue-crowned Chlorophonia",
    "Blue-footed Booby",
    "Blue-fronted Parrotlet",
    "Blue-gray Gnatcatcher",
    "Blue-gray Tanager",
    "Blue-headed Hummingbird",
    "Blue-headed Parrot",
    "Blue-headed Quail-Dove",
    "Blue-headed Vireo",
    "Blue-tailed Hummingbird",
    "Blue-throated Goldentail",
    "Blue-throated Motmot",
    "Blue-throated Mountain-gem",
    "Blue-vented Hummingbird",
    "Blue-winged Teal",
    "Blue-winged Warbler",
    "Bluethroat",
    "Blyth's Reed Warbler",
    "Boat-billed Flycatcher",
    "Boat-billed Heron",
    "Boat-tailed Grackle",
    "Bobolink",
    "Bohemian Waxwing",
    "Bonaparte's Gull",
    "Boreal Chickadee",
    "Boreal Owl",
    "Botteri's Sparrow",
    "Boucard's Wren",
    "Brace's Emerald",
    "Brambling",
    "Bran-colored Flycatcher",
    "Brandt's Cormorant",
    "Brant",
    "Brewer's Blackbird",
    "Brewer's Sparrow",
    "Bridled Quail-Dove",
    "Bridled Sparrow",
    "Bridled Tern",
    "Bridled Titmouse",
    "Bright-rumped Attila",
    "Bristle-thighed Curlew",
    "Broad-billed Hummingbird",
    "Broad-billed Motmot",
    "Broad-billed Sandpiper",
    "Broad-billed Tody",
    "Broad-tailed Hummingbird",
    "Broad-winged Hawk",
    "Bronze Mannikin",
    "Bronze-olive Pygmy-Tyrant",
    "Bronze-tailed Plumeleteer",
    "Bronzed Cowbird",
    "Bronzy Hermit",
    "Brown Booby",
    "Brown Creeper",
    "Brown Jay",
    "Brown Noddy",
    "Brown Pelican",
    "Brown Shrike",
    "Brown Thrasher",
    "Brown Trembler",
    "Brown Violetear",
    "Brown-backed Solitaire",
    "Brown-billed Scythebill",
    "Brown-capped Rosy-Finch",
    "Brown-capped Tyrannulet",
    "Brown-capped Vireo",
    "Brown-chested Martin",
    "Brown-crested Flycatcher",
    "Brown-headed Cowbird",
    "Brown-headed Nuthatch",
    "Brown-hooded Parrot",
    "Brown-throated Parakeet",
    "Brownish Twistwing",
    "Budgerigar",
    "Buff-bellied Hummingbird",
    "Buff-breasted Flycatcher",
    "Buff-breasted Sandpiper",
    "Buff-breasted Wren",
    "Buff-collared Nightjar",
    "Buff-fronted Foliage-gleaner",
    "Buff-fronted Quail-Dove",
    "Buff-rumped Warbler",
    "Buff-throated Saltator",
    "Bufflehead",
    "Buffy Tuftedcheek",
    "Buffy-crowned Wood-Partridge",
    "Buller's Shearwater",
    "Bullock's Oriole",
    "Bulwer's Petrel",
    "Bumblebee Hummingbird",
    "Burrowing Owl",
    "Bushtit",
    "Bushy-crested Jay",
    "Cabanis's Ground-Sparrow",
    "Cabanis's Wren",
    "Cackling Goose",
    "Cactus Wren",
    "California Condor",
    "California Gnatcatcher",
    "California Gull",
    "California Quail",
    "California Scrub-Jay",
    "California Thrasher",
    "California Towhee",
    "Calliope Hummingbird",
    "Canada Goose",
    "Canada Jay",
    "Canada Warbler",
    "Canebrake Wren",
    "Canivet's Emerald",
    "Canvasback",
    "Canyon Towhee",
    "Canyon Wren",
    "Cape May Warbler",
    "Cape Verde Shearwater",
    "Capped Heron",
    "Carib Grackle",
    "Caribbean Dove",
    "Caribbean Elaenia",
    "Caribbean Martin",
    "Carmiol's Tanager",
    "Carolina Chickadee",
    "Carolina Parakeet",
    "Carolina Wren",
    "Caspian Tern",
    "Cassia Crossbill",
    "Cassin's Auklet",
    "Cassin's Finch",
    "Cassin's Kingbird",
    "Cassin's Sparrow",
    "Cassin's Vireo",
    "Cattle Tyrant",
    "Cave Swallow",
    "Cedar Waxwing",
    "Central American Pygmy-Owl",
    "Cerulean Warbler",
    "Chapman's Swift",
    "Charming Hummingbird",
    "Chatham Albatross",
    "Checker-throated Stipplethroat",
    "Chestnut Munia",
    "Chestnut-backed Antbird",
    "Chestnut-backed Chickadee",
    "Chestnut-bellied Cuckoo",
    "Chestnut-bellied Seed-Finch",
    "Chestnut-capped Brushfinch",
    "Chestnut-capped Warbler",
    "Chestnut-collared Longspur",
    "Chestnut-collared Swift",
    "Chestnut-colored Woodpecker",
    "Chestnut-fronted Macaw",
    "Chestnut-headed Oropendola",
    "Chestnut-sided Shrike-Vireo",
    "Chestnut-sided Warbler",
    "Chihuahuan Meadowlark",
    "Chihuahuan Raven",
    "Chimney Swift",
    "Chinese Egret",
    "Chinese Pond-Heron",
    "Chinese Sparrowhawk",
    "Chipping Sparrow",
    "Chiriqui Foliage-gleaner",
    "Chiriqui Quail-Dove",
    "Choco Elaenia",
    "Choco Manakin",
    "Choco Screech-Owl",
    "Choco Sirystes",
    "Choco Tapaculo",
    "Choco Tinamou",
    "Choco Toucan",
    "Christmas Shearwater",
    "Chuck-will's-widow",
    "Chukar",
    "Cinereous Becard",
    "Cinereous Owl",
    "Cinnamon Becard",
    "Cinnamon Hummingbird",
    "Cinnamon Teal",
    "Cinnamon Woodpecker",
    "Cinnamon-bellied Flowerpiercer",
    "Cinnamon-bellied Saltator",
    "Cinnamon-rumped Seedeater",
    "Cinnamon-tailed Sparrow",
    "Citreoline Trogon",
    "Citrine Wagtail",
    "Clapper Rail",
    "Clarion Wren",
    "Clark's Grebe",
    "Clark's Nutcracker",
    "Clay-colored Sparrow",
    "Clay-colored Thrush",
    "Cliff Swallow",
    "Cocoa Thrush",
    "Cocoa Woodcreeper",
    "Cocoi Heron",
    "Cocos Booby",
    "Cocos Cuckoo",
    "Cocos Finch",
    "Cocos Tyrannulet",
    "Coiba Spinetail",
    "Colima Pygmy-Owl",
    "Colima Warbler",
    "Collared Aracari",
    "Collared Forest-Falcon",
    "Collared Plover",
    "Collared Pratincole",
    "Collared Redstart",
    "Collared Towhee",
    "Collared Trogon",
    "Colombian Crake",
    "Comb Duck",
    "Common Black Hawk",
    "Common Chaffinch",
    "Common Chiffchaff",
    "Common Chlorospingus",
    "Common Crane",
    "Common Cuckoo",
    "Common Eider",
    "Common Gallinule",
    "Common Goldeneye",
    "Common Grackle",
    "Common Greenshank",
    "Common Ground Dove",
    "Common Gull",
    "Common Loon",
    "Common Merganser",
    "Common Murre",
    "Common Myna",
    "Common Nighthawk",
    "Common Pauraque",
    "Common Pochard",
    "Common Poorwill",
    "Common Potoo",
    "Common Raven",
    "Common Redshank",
    "Common Redstart",
    "Common Ringed Plover",
    "Common Rosefinch",
    "Common Sandpiper",
    "Common Scoter",
    "Common Shelduck",
    "Common Snipe",
    "Common Swift",
    "Common Tern",
    "Common Tody-Flycatcher",
    "Common Waxbill",
    "Common Wood-Pigeon",
    "Common Yellowthroat",
    "Connecticut Warbler",
    "Cook's Petrel",
    "Cooper's Hawk",
    "Coppery-headed Emerald",
    "Corn Crake",
    "Cory's Shearwater",
    "Costa Rican Brushfinch",
    "Costa Rican Pygmy-Owl",
    "Costa Rican Swift",
    "Costa Rican Warbler",
    "Costa's Hummingbird",
    "Couch's Kingbird",
    "Cozumel Emerald",
    "Cozumel Thrasher",
    "Cozumel Vireo",
    "Cozumel Wren",
    "Crane Hawk",
    "Craveri's Murrelet",
    "Crescent-chested Warbler",
    "Crested Auklet",
    "Crested Bobwhite",
    "Crested Caracara",
    "Crested Eagle",
    "Crested Guan",
    "Crested Myna",
    "Crested Oropendola",
    "Crested Owl",
    "Crested Quail-Dove",
    "Crimson-backed Tanager",
    "Crimson-bellied Woodpecker",
    "Crimson-collared Grosbeak",
    "Crimson-collared Tanager",
    "Crimson-crested Woodpecker",
    "Crimson-fronted Parakeet",
    "Crissal Thrasher",
    "Crowned Slaty Flycatcher",
    "Crowned Woodnymph",
    "Cuban Amazon",
    "Cuban Black Hawk",
    "Cuban Blackbird",
    "Cuban Bullfinch",
    "Cuban Crow",
    "Cuban Emerald",
    "Cuban Gnatcatcher",
    "Cuban Grassquit",
    "Cuban Green Woodpecker",
    "Cuban Kite",
    "Cuban Macaw",
    "Cuban Martin",
    "Cuban Nightjar",
    "Cuban Oriole",
    "Cuban Palm-Crow",
    "Cuban Parakeet",
    "Cuban Pewee",
    "Cuban Pygmy-Owl",
    "Cuban Solitaire",
    "Cuban Tody",
    "Cuban Trogon",
    "Cuban Vireo",
    "Curlew Sandpiper",
    "Curve-billed Thrasher",
    "Dark Pewee",
    "Dark-billed Cuckoo",
    "Dark-eyed Junco",
    "Dark-sided Flycatcher",
    "Dickcissel",
    "Dot-winged Antwren",
    "Double-banded Graytail",
    "Double-crested Cormorant",
    "Double-striped Thick-knee",
    "Double-toothed Kite",
    "Dovekie",
    "Downy Woodpecker",
    "Dull-mantled Antbird",
    "Dunlin",
    "Dusky Antbird",
    "Dusky Flycatcher",
    "Dusky Grouse",
    "Dusky Hummingbird",
    "Dusky Nightjar",
    "Dusky Pigeon",
    "Dusky Thrush",
    "Dusky Warbler",
    "Dusky-backed Jacamar",
    "Dusky-capped Flycatcher",
    "Dusky-faced Tanager",
    "Dwarf Cuckoo",
    "Dwarf Jay",
    "Dwarf Vireo",
    "Eared Dove",
    "Eared Grebe",
    "Eared Poorwill",
    "Eared Quetzal",
    "Eastern Bluebird",
    "Eastern Cattle-Egret",
    "Eastern Chat-Tanager",
    "Eastern Kingbird",
    "Eastern Meadowlark",
    "Eastern Phoebe",
    "Eastern Screech-Owl",
    "Eastern Spot-billed Duck",
    "Eastern Towhee",
    "Eastern Whip-poor-will",
    "Eastern Wood-Pewee",
    "Eastern Yellow Wagtail",
    "Egyptian Goose",
    "Elegant Euphonia",
    "Elegant Quail",
    "Elegant Tern",
    "Elegant Trogon",
    "Elf Owl",
    "Elfin-woods Warbler",
    "Emerald Tanager",
    "Emerald-chinned Hummingbird",
    "Emperor Goose",
    "Eskimo Curlew",
    "Euler's Flycatcher",
    "Eurasian Bittern",
    "Eurasian Blackbird",
    "Eurasian Bullfinch",
    "Eurasian Collared-Dove",
    "Eurasian Coot",
    "Eurasian Curlew",
    "Eurasian Dotterel",
    "Eurasian Goshawk",
    "Eurasian Hobby",
    "Eurasian Hoopoe",
    "Eurasian Jackdaw",
    "Eurasian Kestrel",
    "Eurasian Moorhen",
    "Eurasian Oystercatcher",
    "Eurasian Siskin",
    "Eurasian Skylark",
    "Eurasian Sparrowhawk",
    "Eurasian Spoonbill",
    "Eurasian Tree Sparrow",
    "Eurasian Wigeon",
    "Eurasian Woodcock",
    "Eurasian Wryneck",
    "European Bee-eater",
    "European Golden-Plover",
    "European Goldfinch",
    "European Herring Gull",
    "European Robin",
    "European Starling",
    "European Storm-Petrel",
    "European Turtle-Dove",
    "Evening Grosbeak",
    "Eye-ringed Flatbill",
    "Eyebrowed Thrush",
    "Falcated Duck",
    "Fan-tailed Warbler",
    "Far Eastern Curlew",
    "Fasciated Antshrike",
    "Fasciated Tiger-Heron",
    "Fawn-throated Foliage-gleaner",
    "Fea's Petrel",
    "Fernandina's Flicker",
    "Ferruginous Hawk",
    "Ferruginous Pygmy-Owl",
    "Field Sparrow",
    "Fieldfare",
    "Fiery-billed Aracari",
    "Fiery-throated Hummingbird",
    "Fish Crow",
    "Five-striped Sparrow",
    "Flame-colored Tanager",
    "Flame-rumped Tanager",
    "Flame-throated Warbler",
    "Flammulated Flycatcher",
    "Flammulated Owl",
    "Flat-billed Vireo",
    "Flesh-footed Shearwater",
    "Florida Scrub-Jay",
    "Forest Elaenia",
    "Forest Thrush",
    "Fork-tailed Flycatcher",
    "Fork-tailed Storm-Petrel",
    "Forster's Tern",
    "Fox Sparrow",
    "Franklin's Gull",
    "Fulvous Owl",
    "Fulvous Whistling-Duck",
    "Fulvous-vented Euphonia",
    "Gadwall",
    "Galapagos Petrel",
    "Galapagos Shearwater",
    "Gambel's Quail",
    "Garden Emerald",
    "Garganey",
    "Garnet-throated Hummingbird",
    "Gartered Trogon",
    "Giant Cowbird",
    "Giant Kingbird",
    "Giant Wren",
    "Gila Woodpecker",
    "Gilded Flicker",
    "Glaucous Gull",
    "Glaucous-winged Gull",
    "Glossy Ibis",
    "Glow-throated Hummingbird",
    "Golden Eagle",
    "Golden Swallow",
    "Golden Vireo",
    "Golden-bellied Flycatcher",
    "Golden-browed Chlorophonia",
    "Golden-browed Warbler",
    "Golden-cheeked Warbler",
    "Golden-cheeked Woodpecker",
    "Golden-collared Manakin",
    "Golden-crowned Emerald",
    "Golden-crowned Kinglet",
    "Golden-crowned Spadebill",
    "Golden-crowned Sparrow",
    "Golden-crowned Warbler",
    "Golden-fronted Greenlet",
    "Golden-fronted Woodpecker",
    "Golden-green Woodpecker",
    "Golden-headed Manakin",
    "Golden-headed Quetzal",
    "Golden-hooded Tanager",
    "Golden-naped Woodpecker",
    "Golden-olive Woodpecker",
    "Golden-winged Warbler",
    "Grace's Warbler",
    "Grand Cayman Bullfinch",
    "Grand Cayman Thrush",
    "Grass Wren",
    "Grasshopper Sparrow",
    "Grassland Yellow-Finch",
    "Gray Bunting",
    "Gray Catbird",
    "Gray Flycatcher",
    "Gray Gull",
    "Gray Hawk",
    "Gray Heron",
    "Gray Kingbird",
    "Gray Nightjar",
    "Gray Partridge",
    "Gray Silky-flycatcher",
    "Gray Thrasher",
    "Gray Trembler",
    "Gray Vireo",
    "Gray Wagtail",
    "Gray-and-gold Tanager",
    "Gray-barred Wren",
    "Gray-bellied Hawk",
    "Gray-breasted Crake",
    "Gray-breasted Martin",
    "Gray-breasted Wood-Wren",
    "Gray-breasted Woodpecker",
    "Gray-capped Cuckoo",
    "Gray-capped Flycatcher",
    "Gray-cheeked Nunlet",
    "Gray-cheeked Thrush",
    "Gray-chested Dove",
    "Gray-collared Becard",
    "Gray-cowled Wood-Rail",
    "Gray-crowned Palm-Tanager",
    "Gray-crowned Rosy-Finch",
    "Gray-crowned Woodpecker",
    "Gray-crowned Yellowthroat",
    "Gray-faced Petrel",
    "Gray-fronted Quail-Dove",
    "Gray-headed Chachalaca",
    "Gray-headed Chickadee",
    "Gray-headed Dove",
    "Gray-headed Kite",
    "Gray-headed Piprites",
    "Gray-headed Swamphen",
    "Gray-headed Tanager",
    "Gray-hooded Gull",
    "Gray-lined Hawk",
    "Gray-rumped Swift",
    "Gray-streaked Flycatcher",
    "Gray-tailed Tattler",
    "Gray-throated Chat",
    "Gray-throated Leaftosser",
    "Graylag Goose",
    "Great Antshrike",
    "Great Black Hawk",
    "Great Black-backed Gull",
    "Great Blue Heron",
    "Great Cormorant",
    "Great Crested Flycatcher",
    "Great Curassow",
    "Great Egret",
    "Great Frigatebird",
    "Great Gray Owl",
    "Great Green Macaw",
    "Great Horned Owl",
    "Great Jacamar",
    "Great Kiskadee",
    "Great Knot",
    "Great Lizard-Cuckoo",
    "Great Potoo",
    "Great Shearwater",
    "Great Skua",
    "Great Spotted Woodpecker",
    "Great Swallow-tailed Swift",
    "Great Tinamou",
    "Great Tit",
    "Great-tailed Grackle",
    "Greater Ani",
    "Greater Antillean Bullfinch",
    "Greater Antillean Elaenia",
    "Greater Antillean Grackle",
    "Greater Pewee",
    "Greater Prairie-Chicken",
    "Greater Roadrunner",
    "Greater Sage-Grouse",
    "Greater Sand-Plover",
    "Greater Scaup",
    "Greater White-fronted Goose",
    "Greater Yellowlegs",
    "Green Hermit",
    "Green Heron",
    "Green Honeycreeper",
    "Green Ibis",
    "Green Jay",
    "Green Kingfisher",
    "Green Mango",
    "Green Parakeet",
    "Green Sandpiper",
    "Green Shrike-Vireo",
    "Green Thorntail",
    "Green-and-rufous Kingfisher",
    "Green-backed Sparrow",
    "Green-breasted Mango",
    "Green-breasted Mountain-gem",
    "Green-crowned Brilliant",
    "Green-fronted Hummingbird",
    "Green-fronted Lancebill",
    "Green-naped Tanager",
    "Green-rumped Parrotlet",
    "Green-striped Brushfinch",
    "Green-tailed Towhee",
    "Green-tailed Warbler",
    "Green-throated Carib",
    "Green-throated Mountain-gem",
    "Green-winged Teal",
    "Greenish Elaenia",
    "Greenish Puffleg",
    "Grenada Dove",
    "Grenada Flycatcher",
    "Grenada Wren",
    "Groove-billed Ani",
    "Guadalupe Caracara",
    "Guadalupe Junco",
    "Guadalupe Murrelet",
    "Guadalupe Storm-Petrel",
    "Guadeloupe Woodpecker",
    "Guanay Cormorant",
    "Guatemalan Flicker",
    "Guatemalan Tyrannulet",
    "Gull-billed Tern",
    "Gundlach's Hawk",
    "Gunnison Sage-Grouse",
    "Gyrfalcon",
    "Hairy Woodpecker",
    "Hammond's Flycatcher",
    "Happy Wren",
    "Harlequin Duck",
    "Harpy Eagle",
    "Harris's Hawk",
    "Harris's Sparrow",
    "Hawaiian Petrel",
    "Hawfinch",
    "Heermann's Gull",
    "Helmeted Guineafowl",
    "Hen Harrier",
    "Henslow's Sparrow",
    "Hepatic Tanager",
    "Herald Petrel",
    "Hermit Thrush",
    "Hermit Warbler",
    "Highland Guan",
    "Highland Tinamou",
    "Himalayan Snowcock",
    "Hispaniolan Amazon",
    "Hispaniolan Crossbill",
    "Hispaniolan Emerald",
    "Hispaniolan Euphonia",
    "Hispaniolan Lizard-Cuckoo",
    "Hispaniolan Mango",
    "Hispaniolan Nightjar",
    "Hispaniolan Oriole",
    "Hispaniolan Palm-Crow",
    "Hispaniolan Parakeet",
    "Hispaniolan Pewee",
    "Hispaniolan Spindalis",
    "Hispaniolan Trogon",
    "Hispaniolan Woodpecker",
    "Hoffmann's Woodpecker",
    "Honduran Emerald",
    "Hooded Crane",
    "Hooded Grosbeak",
    "Hooded Merganser",
    "Hooded Oriole",
    "Hooded Tanager",
    "Hooded Warbler",
    "Hooded Yellowthroat",
    "Hook-billed Kite",
    "Horned Grebe",
    "Horned Guan",
    "Horned Lark",
    "Horned Puffin",
    "House Finch",
    "House Sparrow",
    "Hudsonian Godwit",
    "Humboldt's Sapphire",
    "Hutton's Vireo",
    "Iceland Gull",
    "Icterine Warbler",
    "Imperial Amazon",
    "Imperial Woodpecker",
    "Inagua Woodstar",
    "Inca Dove",
    "Inca Tern",
    "Indian Silverbill",
    "Indigo Bunting",
    "Island Scrub-Jay",
    "Isthmian Wren",
    "Ivory Gull",
    "Ivory-billed Woodcreeper",
    "Ivory-billed Woodpecker",
    "Jabiru",
    "Jack Snipe",
    "Jamaican Becard",
    "Jamaican Blackbird",
    "Jamaican Crow",
    "Jamaican Elaenia",
    "Jamaican Euphonia",
    "Jamaican Lizard-Cuckoo",
    "Jamaican Mango",
    "Jamaican Oriole",
    "Jamaican Owl",
    "Jamaican Pauraque",
    "Jamaican Petrel",
    "Jamaican Pewee",
    "Jamaican Spindalis",
    "Jamaican Tody",
    "Jamaican Vireo",
    "Jamaican Woodpecker",
    "Java Sparrow",
    "Jet Antbird",
    "Jouanin's Petrel",
    "Juan Fernandez Petrel",
    "Juniper Titmouse",
    "Kalinago Wren",
    "Kamchatka Leaf Warbler",
    "Keel-billed Motmot",
    "Keel-billed Toucan",
    "Kelp Gull",
    "Kentish Plover",
    "Kentucky Warbler",
    "Kermadec Petrel",
    "Key West Quail-Dove",
    "Killdeer",
    "King Eider",
    "King Rail",
    "King Vulture",
    "Kirtland's Warbler",
    "Kittlitz's Murrelet",
    "La Sagra's Flycatcher",
    "La Selle Thrush",
    "Labrador Duck",
    "Ladder-backed Woodpecker",
    "Lance-tailed Manakin",
    "Lanceolated Monklet",
    "Lanceolated Warbler",
    "Lapland Longspur",
    "Large-billed Seed-Finch",
    "Large-billed Tern",
    "Large-footed Finch",
    "Lark Bunting",
    "Lark Sparrow",
    "Lattice-tailed Trogon",
    "Laughing Falcon",
    "Laughing Gull",
    "Lawrence's Goldfinch",
    "Laysan Albatross",
    "Lazuli Bunting",
    "Leach's Storm-Petrel",
    "Least Auklet",
    "Least Bittern",
    "Least Flycatcher",
    "Least Grebe",
    "Least Pauraque",
    "Least Sandpiper",
    "Least Storm-Petrel",
    "Least Tern",
    "LeConte's Sparrow",
    "LeConte's Thrasher",
    "Lemon-spectacled Tanager",
    "Lesser Antillean Bullfinch",
    "Lesser Antillean Euphonia",
    "Lesser Antillean Flycatcher",
    "Lesser Antillean Pewee",
    "Lesser Antillean Saltator",
    "Lesser Antillean Swift",
    "Lesser Antillean Tanager",
    "Lesser Black-backed Gull",
    "Lesser Elaenia",
    "Lesser Frigatebird",
    "Lesser Goldfinch",
    "Lesser Greenlet",
    "Lesser Ground-Cuckoo",
    "Lesser Kiskadee",
    "Lesser Nighthawk",
    "Lesser Prairie-Chicken",
    "Lesser Roadrunner",
    "Lesser Scaup",
    "Lesser Swallow-tailed Swift",
    "Lesser Violetear",
    "Lesser White-fronted Goose",
    "Lesser Whitethroat",
    "Lesser Yellow-headed Vulture",
    "Lesser Yellowlegs",
    "Lesson's Motmot",
    "Lesson's Seedeater",
    "Lewis's Woodpecker",
    "Light-mantled Albatross",
    "Lilac-crowned Amazon",
    "Limpkin",
    "Lincoln's Sparrow",
    "Lineated Foliage-gleaner",
    "Lineated Woodpecker",
    "Lined Seedeater",
    "Little Bittern",
    "Little Blue Heron",
    "Little Bunting",
    "Little Cuckoo",
    "Little Curlew",
    "Little Egret",
    "Little Gull",
    "Little Ringed Plover",
    "Little Stint",
    "Little Swift",
    "Little Tinamou",
    "Loggerhead Kingbird",
    "Loggerhead Shrike",
    "Long-billed Curlew",
    "Long-billed Dowitcher",
    "Long-billed Gnatwren",
    "Long-billed Hermit",
    "Long-billed Murrelet",
    "Long-billed Starthroat",
    "Long-billed Thrasher",
    "Long-eared Owl",
    "Long-legged Buzzard",
    "Long-tailed Duck",
    "Long-tailed Jaeger",
    "Long-tailed Manakin",
    "Long-tailed Silky-flycatcher",
    "Long-tailed Tyrant",
    "Long-tailed Wood-Partridge",
    "Long-toed Stint",
    "Long-winged Harrier",
    "Louisiana Waterthrush",
    "Lovely Cotinga",
    "Lucifer Hummingbird",
    "Lucy's Warbler",
    "MacGillivray's Warbler",
    "Magenta-throated Woodstar",
    "Magnificent Frigatebird",
    "Magnolia Warbler",
    "Maguari Stork",
    "Mallard",
    "Mangrove Cuckoo",
    "Mangrove Hummingbird",
    "Mangrove Rail",
    "Mangrove Swallow",
    "Mangrove Vireo",
    "Manx Shearwater",
    "Marbled Godwit",
    "Marbled Murrelet",
    "Marbled Wood-Quail",
    "Markham's Storm-Petrel",
    "Maroon-chested Ground Dove",
    "Maroon-fronted Parrot",
    "Marsh Sandpiper",
    "Marsh Wren",
    "Martinique Oriole",
    "Martinique Thrasher",
    "Masked Booby",
    "Masked Duck",
    "Masked Tityra",
    "Mayan Antthrush",
    "McKay's Bunting",
    "Meadow Pipit",
    "Mealy Amazon",
    "Medium Egret",
    "Melodious Blackbird",
    "Merlin",
    "Mexican Chickadee",
    "Mexican Duck",
    "Mexican Hermit",
    "Mexican Jay",
    "Mexican Parrotlet",
    "Mexican Sheartail",
    "Mexican Violetear",
    "Mexican Whip-poor-will",
    "Mexican Woodnymph",
    "Middendorff's Grasshopper Warbler",
    "Middle American Leaftosser",
    "Middle American Screech-Owl",
    "Military Macaw",
    "Mississippi Kite",
    "Mistle Thrush",
    "Mistletoe Tyrannulet",
    "Mitred Parakeet",
    "Monk Parakeet",
    "Montezuma Oropendola",
    "Montezuma Quail",
    "Montserrat Oriole",
    "Morelet's Seedeater",
    "Mottled Duck",
    "Mottled Owl",
    "Mottled Petrel",
    "Mountain Bluebird",
    "Mountain Chickadee",
    "Mountain Elaenia",
    "Mountain Plover",
    "Mountain Quail",
    "Mountain Thrush",
    "Mountain Trogon",
    "Mourning Dove",
    "Mourning Warbler",
    "Mouse-colored Tyrannulet",
    "Moustached Antwren",
    "Mugimaki Flycatcher",
    "Murphy's Petrel",
    "Muscovy Duck",
    "Mute Swan",
    "Nanday Parakeet",
    "Narcissus Flycatcher",
    "Narrow-billed Tody",
    "Nashville Warbler",
    "Naumann's Thrush",
    "Nava's Wren",
    "Nazca Booby",
    "Nelson's Sparrow",
    "Neotropic Cormorant",
    "Newell's Shearwater",
    "Nicaraguan Grackle",
    "Nicaraguan Seed-Finch",
    "Nightingale Wren",
    "Northern Barred-Woodcreeper",
    "Northern Beardless-Tyrannulet",
    "Northern Bentbill",
    "Northern Black-throated Trogon",
    "Northern Bobwhite",
    "Northern Boobook",
    "Northern Cardinal",
    "Northern Emerald-Toucanet",
    "Northern Flicker",
    "Northern Fulmar",
    "Northern Gannet",
    "Northern Giant-Petrel",
    "Northern Harrier",
    "Northern Hawk Owl",
    "Northern House Wren",
    "Northern Jacana",
    "Northern Lapwing",
    "Northern Mockingbird",
    "Northern Parula",
    "Northern Pintail",
    "Northern Plain-Xenops",
    "Northern Potoo",
    "Northern Pygmy-Owl",
    "Northern Red Bishop",
    "Northern Rough-winged Swallow",
    "Northern Saw-whet Owl",
    "Northern Schiffornis",
    "Northern Screamer",
    "Northern Scrub-Flycatcher",
    "Northern Shoveler",
    "Northern Shrike",
    "Northern Tropical Pewee",
    "Northern Waterthrush",
    "Northern Wheatear",
    "Northern White-fringed Antwren",
    "Nuttall's Woodpecker",
    "Nutting's Flycatcher",
    "Oak Titmouse",
    "Oaxaca Sparrow",
    "Ocellated Antbird",
    "Ocellated Crake",
    "Ocellated Poorwill",
    "Ocellated Quail",
    "Ocellated Thrasher",
    "Ocellated Turkey",
    "Ochraceous Pewee",
    "Ochraceous Wren",
    "Ochre-bellied Flycatcher",
    "Ochre-breasted Antpitta",
    "Ochre-lored Flatbill",
    "Ochre-throated Foliage-gleaner",
    "Oilbird",
    "Olivaceous Piculet",
    "Olivaceous Woodcreeper",
    "Olive Sparrow",
    "Olive Warbler",
    "Olive-backed Euphonia",
    "Olive-backed Pipit",
    "Olive-backed Quail-Dove",
    "Olive-capped Warbler",
    "Olive-crowned Yellowthroat",
    "Olive-gray Saltator",
    "Olive-sided Flycatcher",
    "Olive-streaked Flycatcher",
    "Olive-striped Flycatcher",
    "Olive-throated Parakeet",
    "One-colored Becard",
    "Orange Oriole",
    "Orange-bellied Euphonia",
    "Orange-billed Nightingale-Thrush",
    "Orange-billed Sparrow",
    "Orange-breasted Bunting",
    "Orange-breasted Falcon",
    "Orange-cheeked Waxbill",
    "Orange-chinned Parakeet",
    "Orange-collared Manakin",
    "Orange-crowned Oriole",
    "Orange-crowned Warbler",
    "Orange-fronted Parakeet",
    "Orange-winged Amazon",
    "Orangequit",
    "Orchard Oriole",
    "Oriental Cuckoo",
    "Oriental Greenfinch",
    "Oriental Honey-buzzard",
    "Oriental Pratincole",
    "Oriental Scops-Owl",
    "Oriental Turtle-Dove",
    "Oriente Warbler",
    "Orinoco Goose",
    "Ornate Hawk-Eagle",
    "Osprey",
    "Ovenbird",
    "Pacific Antwren",
    "Pacific Golden-Plover",
    "Pacific Loon",
    "Pacific Parakeet",
    "Pacific Screech-Owl",
    "Pacific Swift",
    "Pacific Wren",
    "Paint-billed Crake",
    "Painted Bunting",
    "Painted Parakeet",
    "Painted Redstart",
    "Pale-bellied Hermit",
    "Pale-billed Woodpecker",
    "Pale-breasted Spinetail",
    "Pale-eyed Pygmy-Tyrant",
    "Pale-vented Pigeon",
    "Pale-vented Thrush",
    "Pallas's Bunting",
    "Pallas's Grasshopper Warbler",
    "Pallas's Gull",
    "Pallas's Leaf Warbler",
    "Pallas's Rosefinch",
    "Pallid Harrier",
    "Palm Tanager",
    "Palm Warbler",
    "Palmchat",
    "Panama Flycatcher",
    "Parakeet Auklet",
    "Parasitic Jaeger",
    "Parkinson's Petrel",
    "Passenger Pigeon",
    "Pearl Kite",
    "Pearly-breasted Cuckoo",
    "Pearly-eyed Thrasher",
    "Pechora Pipit",
    "Pectoral Sandpiper",
    "Peg-billed Finch",
    "Pelagic Cormorant",
    "Peregrine Falcon",
    "Peruvian Booby",
    "Peruvian Pelican",
    "Phainopepla",
    "Pheasant Cuckoo",
    "Philadelphia Vireo",
    "Pied Imperial-Pigeon",
    "Pied Puffbird",
    "Pied Water-Tyrant",
    "Pied Wheatear",
    "Pied-billed Grebe",
    "Pigeon Guillemot",
    "Pileated Flycatcher",
    "Pileated Woodpecker",
    "Pin-tailed Snipe",
    "Pin-tailed Whydah",
    "Pine Bunting",
    "Pine Flycatcher",
    "Pine Grosbeak",
    "Pine Siskin",
    "Pine Warbler",
    "Pink-footed Goose",
    "Pink-footed Shearwater",
    "Pink-headed Warbler",
    "Pinnated Bittern",
    "Pinyon Jay",
    "Piping Plover",
    "Piping Woodcreeper",
    "Piratic Flycatcher",
    "Pirre Chlorospingus",
    "Pirre Hummingbird",
    "Pirre Warbler",
    "Plain Antvireo",
    "Plain Chachalaca",
    "Plain Pigeon",
    "Plain-breasted Ground Dove",
    "Plain-brown Woodcreeper",
    "Plain-capped Starthroat",
    "Plain-colored Tanager",
    "Plumbeous Hawk",
    "Plumbeous Kite",
    "Plumbeous Pigeon",
    "Plumbeous Vireo",
    "Plumbeous Warbler",
    "Pomarine Jaeger",
    "Prairie Falcon",
    "Prairie Warbler",
    "Prong-billed Barbet",
    "Prothonotary Warbler",
    "Providence Petrel",
    "Puerto Rican Amazon",
    "Puerto Rican Bullfinch",
    "Puerto Rican Emerald",
    "Puerto Rican Euphonia",
    "Puerto Rican Flycatcher",
    "Puerto Rican Lizard-Cuckoo",
    "Puerto Rican Mango",
    "Puerto Rican Nightjar",
    "Puerto Rican Oriole",
    "Puerto Rican Owl",
    "Puerto Rican Parakeet",
    "Puerto Rican Spindalis",
    "Puerto Rican Tanager",
    "Puerto Rican Tody",
    "Puerto Rican Vireo",
    "Puerto Rican Woodpecker",
    "Purple Finch",
    "Purple Gallinule",
    "Purple Heron",
    "Purple Honeycreeper",
    "Purple Martin",
    "Purple Sandpiper",
    "Purple-crowned Fairy",
    "Purple-throated Carib",
    "Purple-throated Fruitcrow",
    "Purple-throated Mountain-gem",
    "Purple-throated Woodstar",
    "Purplish-backed Jay",
    "Purplish-backed Quail-Dove",
    "Pygmy Nuthatch",
    "Pyrrhuloxia",
    "Razorbill",
    "Red Avadavat",
    "Red Crossbill",
    "Red Junglefowl",
    "Red Knot",
    "Red Phalarope",
    "Red Warbler",
    "Red-and-green Macaw",
    "Red-backed Shrike",
    "Red-bellied Woodpecker",
    "Red-billed Pigeon",
    "Red-billed Scythebill",
    "Red-billed Streamertail",
    "Red-billed Tropicbird",
    "Red-breasted Chat",
    "Red-breasted Meadowlark",
    "Red-breasted Merganser",
    "Red-breasted Nuthatch",
    "Red-breasted Sapsucker",
    "Red-capped Manakin",
    "Red-cockaded Woodpecker",
    "Red-crowned Amazon",
    "Red-crowned Ant-Tanager",
    "Red-crowned Woodpecker",
    "Red-eyed Vireo",
    "Red-faced Cormorant",
    "Red-faced Spinetail",
    "Red-faced Warbler",
    "Red-flanked Bluetail",
    "Red-footed Booby",
    "Red-footed Falcon",
    "Red-fronted Parrotlet",
    "Red-headed Barbet",
    "Red-headed Tanager",
    "Red-headed Woodpecker",
    "Red-legged Honeycreeper",
    "Red-legged Kittiwake",
    "Red-legged Thrush",
    "Red-lored Amazon",
    "Red-masked Parakeet",
    "Red-naped Sapsucker",
    "Red-necked Amazon",
    "Red-necked Grebe",
    "Red-necked Phalarope",
    "Red-necked Stint",
    "Red-rumped Woodpecker",
    "Red-shouldered Blackbird",
    "Red-shouldered Hawk",
    "Red-tailed Hawk",
    "Red-tailed Tropicbird",
    "Red-throated Ant-Tanager",
    "Red-throated Caracara",
    "Red-throated Loon",
    "Red-throated Pipit",
    "Red-vented Bulbul",
    "Red-whiskered Bulbul",
    "Red-winged Blackbird",
    "Reddish Egret",
    "Redhead",
    "Redpoll",
    "Redwing",
    "Reed Bunting",
    "Resplendent Quetzal",
    "Rhinoceros Auklet",
    "Ridgway's Hawk",
    "Ridgway's Rail",
    "Ring-billed Gull",
    "Ring-necked Duck",
    "Ring-necked Pheasant",
    "Ring-tailed Pigeon",
    "Ringed Kingfisher",
    "Ringed Storm-Petrel",
    "River Warbler",
    "Riverside Wren",
    "Rivoli's Hummingbird",
    "Roadside Hawk",
    "Rock Pigeon",
    "Rock Ptarmigan",
    "Rock Sandpiper",
    "Rock Wren",
    "Rook",
    "Rose-bellied Bunting",
    "Rose-breasted Grosbeak",
    "Rose-ringed Parakeet",
    "Rose-throated Becard",
    "Rose-throated Tanager",
    "Roseate Spoonbill",
    "Roseate Tern",
    "Ross's Goose",
    "Ross's Gull",
    "Rosy Thrush-Tanager",
    "Rosy-faced Lovebird",
    "Rough-legged Hawk",
    "Royal Tern",
    "Ruby-crowned Kinglet",
    "Ruby-throated Hummingbird",
    "Ruby-topaz Hummingbird",
    "Ruddy Crake",
    "Ruddy Duck",
    "Ruddy Foliage-gleaner",
    "Ruddy Ground Dove",
    "Ruddy Pigeon",
    "Ruddy Quail-Dove",
    "Ruddy Treerunner",
    "Ruddy Turnstone",
    "Ruddy Woodcreeper",
    "Ruddy-breasted Seedeater",
    "Ruddy-capped Nightingale-Thrush",
    "Ruddy-tailed Flycatcher",
    "Rufescent Tiger-Heron",
    "Ruff",
    "Ruffed Grouse",
    "Rufous Hummingbird",
    "Rufous Motmot",
    "Rufous Mourner",
    "Rufous Nightjar",
    "Rufous Piha",
    "Rufous Sabrewing",
    "Rufous-and-white Wren",
    "Rufous-backed Robin",
    "Rufous-backed Wren",
    "Rufous-bellied Chachalaca",
    "Rufous-breasted Antthrush",
    "Rufous-breasted Hermit",
    "Rufous-breasted Spinetail",
    "Rufous-breasted Wren",
    "Rufous-browed Peppershrike",
    "Rufous-browed Tyrannulet",
    "Rufous-browed Wren",
    "Rufous-capped Brushfinch",
    "Rufous-capped Warbler",
    "Rufous-collared Robin",
    "Rufous-collared Sparrow",
    "Rufous-crested Coquette",
    "Rufous-crowned Sparrow",
    "Rufous-necked Wood-Rail",
    "Rufous-rumped Antwren",
    "Rufous-tailed Flycatcher",
    "Rufous-tailed Hummingbird",
    "Rufous-tailed Jacamar",
    "Rufous-tailed Robin",
    "Rufous-tailed Rock-Thrush",
    "Rufous-throated Solitaire",
    "Rufous-vented Chachalaca",
    "Rufous-vented Ground-Cuckoo",
    "Rufous-winged Sparrow",
    "Rufous-winged Tanager",
    "Rufous-winged Woodpecker",
    "Russet Antshrike",
    "Russet Nightingale-Thrush",
    "Russet-crowned Motmot",
    "Russet-crowned Quail-Dove",
    "Russet-naped Wood-Rail",
    "Russet-naped Wren",
    "Russet-throated Puffbird",
    "Russet-winged Schiffornis",
    "Rustic Bunting",
    "Rusty Blackbird",
    "Rusty Sparrow",
    "Rusty-crowned Ground-Sparrow",
    "Rusty-margined Flycatcher",
    "Rusty-winged Antwren",
    "Sabine's Gull",
    "Sad Flycatcher",
    "Saffron Finch",
    "Saffron-headed Parrot",
    "Sage Thrasher",
    "Sagebrush Sparrow",
    "Saltmarsh Sparrow",
    "Salvin's Albatross",
    "San Andres Vireo",
    "San Blas Jay",
    "Sanderling",
    "Sandhill Crane",
    "Sandwich Tern",
    "Sapayoa",
    "Sapphire-throated Hummingbird",
    "Sargasso Shearwater",
    "Savanna Hawk",
    "Savannah Sparrow",
    "Say's Phoebe",
    "Scale-crested Pygmy-Tyrant",
    "Scaled Antpitta",
    "Scaled Pigeon",
    "Scaled Quail",
    "Scaly-breasted Hummingbird",
    "Scaly-breasted Munia",
    "Scaly-breasted Thrasher",
    "Scaly-breasted Wren",
    "Scaly-naped Pigeon",
    "Scaly-throated Foliage-gleaner",
    "Scaly-throated Leaftosser",
    "Scarlet Ibis",
    "Scarlet Macaw",
    "Scarlet Tanager",
    "Scarlet-browed Tanager",
    "Scarlet-rumped Cacique",
    "Scarlet-rumped Tanager",
    "Scarlet-thighed Dacnis",
    "Scintillant Hummingbird",
    "Scissor-tailed Flycatcher",
    "Scopoli's Shearwater",
    "Scott's Oriole",
    "Scripps's Murrelet",
    "Scrub Euphonia",
    "Scrub Greenlet",
    "Seaside Sparrow",
    "Sedge Warbler",
    "Sedge Wren",
    "Semipalmated Plover",
    "Semipalmated Sandpiper",
    "Semiplumbeous Hawk",
    "Semper's Warbler",
    "Sepia-capped Flycatcher",
    "Sharp-shinned Hawk",
    "Sharp-tailed Grouse",
    "Sharp-tailed Sandpiper",
    "Sharp-tailed Streamcreeper",
    "Sharpbill",
    "Shining Honeycreeper",
    "Shiny Cowbird",
    "Short-billed Dowitcher",
    "Short-billed Gull",
    "Short-billed Pigeon",
    "Short-crested Coquette",
    "Short-eared Owl",
    "Short-tailed Albatross",
    "Short-tailed Hawk",
    "Short-tailed Nighthawk",
    "Short-tailed Shearwater",
    "Short-tailed Swift",
    "Siberian Accentor",
    "Siberian Blue Robin",
    "Siberian House-Martin",
    "Siberian Pipit",
    "Siberian Rubythroat",
    "Siberian Sand-Plover",
    "Siberian Stonechat",
    "Sierra Madre Sparrow",
    "Silver Pheasant",
    "Silver-throated Tanager",
    "Silvery-fronted Tapaculo",
    "Silvery-throated Jay",
    "Sinaloa Crow",
    "Sinaloa Martin",
    "Sinaloa Wren",
    "Singing Quail",
    "Slate-colored Grosbeak",
    "Slate-colored Seedeater",
    "Slate-colored Solitaire",
    "Slate-headed Tody-Flycatcher",
    "Slate-throated Gnatcatcher",
    "Slate-throated Redstart",
    "Slaty Antwren",
    "Slaty Finch",
    "Slaty Flowerpiercer",
    "Slaty Spinetail",
    "Slaty Vireo",
    "Slaty-backed Forest-Falcon",
    "Slaty-backed Gull",
    "Slaty-backed Nightingale-Thrush",
    "Slaty-breasted Tinamou",
    "Slaty-capped Flycatcher",
    "Slaty-tailed Trogon",
    "Slaty-winged Foliage-gleaner",
    "Slender Sheartail",
    "Slender-billed Curlew",
    "Slender-billed Grackle",
    "Slender-billed Kite",
    "Small-billed Elaenia",
    "Smew",
    "Smith's Longspur",
    "Smoky-brown Woodpecker",
    "Smooth-billed Ani",
    "Snail Kite",
    "Snow Bunting",
    "Snow Goose",
    "Snowcap",
    "Snowy Cotinga",
    "Snowy Egret",
    "Snowy Owl",
    "Snowy Plover",
    "Snowy-bellied Hummingbird",
    "Social Flycatcher",
    "Socorro Dove",
    "Socorro Mockingbird",
    "Socorro Parakeet",
    "Socorro Wren",
    "Solitary Eagle",
    "Solitary Sandpiper",
    "Solitary Snipe",
    "Song Sparrow",
    "Song Thrush",
    "Song Wren",
    "Sooty Grouse",
    "Sooty Shearwater",
    "Sooty Tern",
    "Sooty Thrush",
    "Sooty-capped Chlorospingus",
    "Sooty-faced Finch",
    "Sooty-headed Tyrannulet",
    "Sooty-headed Wren",
    "Sora",
    "South American Leaftosser",
    "South Polar Skua",
    "Southern Beardless-Tyrannulet",
    "Southern Bentbill",
    "Southern House Wren",
    "Southern Lapwing",
    "Southern Martin",
    "Southern Rough-winged Swallow",
    "Spangle-cheeked Tanager",
    "Sparkling-tailed Hummingbird",
    "Speckled Mourner",
    "Speckled Tanager",
    "Spectacled Eider",
    "Spectacled Owl",
    "Spectacled Parrotlet",
    "Spectacled Petrel",
    "Spectacled Thrush",
    "Spiny-faced Antshrike",
    "Spoon-billed Sandpiper",
    "Spot-bellied Bobwhite",
    "Spot-breasted Oriole",
    "Spot-breasted Woodpecker",
    "Spot-breasted Wren",
    "Spot-crowned Antvireo",
    "Spot-crowned Barbet",
    "Spot-crowned Euphonia",
    "Spot-crowned Woodcreeper",
    "Spot-fronted Swift",
    "Spot-tailed Nightjar",
    "Spotted Antbird",
    "Spotted Barbtail",
    "Spotted Crake",
    "Spotted Dove",
    "Spotted Flycatcher",
    "Spotted Rail",
    "Spotted Redshank",
    "Spotted Sandpiper",
    "Spotted Towhee",
    "Spotted Wood-Quail",
    "Spotted Woodcreeper",
    "Spotted Wren",
    "Sprague's Pipit",
    "Spruce Grouse",
    "Squacco Heron",
    "Squirrel Cuckoo",
    "St. Kitts Bullfinch",
    "St. Lucia Amazon",
    "St. Lucia Black Finch",
    "St. Lucia Oriole",
    "St. Lucia Thrasher",
    "St. Lucia Warbler",
    "St. Lucia Wren",
    "St. Vincent Amazon",
    "St. Vincent Wren",
    "Stejneger's Petrel",
    "Stejneger's Scoter",
    "Steller's Eider",
    "Steller's Jay",
    "Steller's Sea-Eagle",
    "Stilt Sandpiper",
    "Stolid Flycatcher",
    "Straight-billed Woodcreeper",
    "Streak-backed Oriole",
    "Streak-breasted Treehunter",
    "Streak-chested Antpitta",
    "Streak-crowned Antvireo",
    "Streak-headed Woodcreeper",
    "Streaked Flycatcher",
    "Streaked Saltator",
    "Streaked Shearwater",
    "Streaked Xenops",
    "Striated Heron",
    "Strickland's Woodpecker",
    "Stripe-breasted Wren",
    "Stripe-cheeked Woodpecker",
    "Stripe-headed Sparrow",
    "Stripe-tailed Hummingbird",
    "Stripe-throated Hermit",
    "Stripe-throated Wren",
    "Striped Cuckoo",
    "Striped Owl",
    "Striped Sparrow",
    "Strong-billed Woodcreeper",
    "Stub-tailed Spadebill",
    "Stygian Owl",
    "Sulphur-bellied Flycatcher",
    "Sulphur-rumped Flycatcher",
    "Sulphur-rumped Tanager",
    "Sulphur-winged Parakeet",
    "Sumichrast's Wren",
    "Summer Tanager",
    "Sunbittern",
    "Sungrebe",
    "Surf Scoter",
    "Surfbird",
    "Swainson's Hawk",
    "Swainson's Thrush",
    "Swainson's Warbler",
    "Swallow Tanager",
    "Swallow-tailed Gull",
    "Swallow-tailed Kite",
    "Swamp Sparrow",
    "Swinhoe's Storm-Petrel",
    "Tacarcuna Chlorospingus",
    "Tacarcuna Tapaculo",
    "Tacarcuna Warbler",
    "Tacarcuna Wood-Quail",
    "Tahiti Petrel",
    "Taiga Bean-Goose",
    "Taiga Flycatcher",
    "Talamanca Hummingbird",
    "Tamaulipas Crow",
    "Tamaulipas Pygmy-Owl",
    "Tawny-breasted Flycatcher",
    "Tawny-capped Euphonia",
    "Tawny-chested Flycatcher",
    "Tawny-collared Nightjar",
    "Tawny-crested Tanager",
    "Tawny-crowned Greenlet",
    "Tawny-faced Gnatwren",
    "Tawny-faced Quail",
    "Tawny-shouldered Blackbird",
    "Tawny-winged Woodcreeper",
    "Temminck's Stint",
    "Tennessee Warbler",
    "Terek Sandpiper",
    "Thick-billed Euphonia",
    "Thick-billed Kingbird",
    "Thick-billed Longspur",
    "Thick-billed Murre",
    "Thick-billed Parrot",
    "Thick-billed Seed-Finch",
    "Thick-billed Vireo",
    "Thick-billed Warbler",
    "Thicket Antpitta",
    "Thicket Tinamou",
    "Three-wattled Bellbird",
    "Timberline Wren",
    "Tiny Hawk",
    "Tody Motmot",
    "Tooth-billed Hummingbird",
    "Torrent Tyrannulet",
    "Townsend's Shearwater",
    "Townsend's Solitaire",
    "Townsend's Storm-Petrel",
    "Townsend's Warbler",
    "Transvolcanic Jay",
    "Tree Pipit",
    "Tree Swallow",
    "Tres Marias Hummingbird",
    "Tricolored Blackbird",
    "Tricolored Heron",
    "Tricolored Munia",
    "Trindade Petrel",
    "Tristram's Storm-Petrel",
    "Tropical Kingbird",
    "Tropical Mockingbird",
    "Tropical Parula",
    "Tropical Royal Flycatcher",
    "Tropical Screech-Owl",
    "Trumpeter Swan",
    "Tufted Duck",
    "Tufted Flycatcher",
    "Tufted Jay",
    "Tufted Puffin",
    "Tufted Titmouse",
    "Tundra Bean-Goose",
    "Tundra Swan",
    "Turkey Vulture",
    "Turquoise Cotinga",
    "Turquoise-browed Motmot",
    "Turquoise-crowned Hummingbird",
    "Tuxtla Quail-Dove",
    "Unicolored Jay",
    "Uniform Crake",
    "Unspotted Saw-whet Owl",
    "Upland Sandpiper",
    "Variable Hawk",
    "Variable Seedeater",
    "Varied Bunting",
    "Varied Solitaire",
    "Varied Thrush",
    "Variegated Flycatcher",
    "Vaux's Swift",
    "Veery",
    "Vega Gull",
    "Velvety Manakin",
    "Venezuelan Troupial",
    "Veracruz Wren",
    "Veraguan Mango",
    "Verdin",
    "Vermilion Flycatcher",
    "Vervain Hummingbird",
    "Vesper Sparrow",
    "Village Weaver",
    "Violaceous Quail-Dove",
    "Violet Sabrewing",
    "Violet-bellied Hummingbird",
    "Violet-capped Hummingbird",
    "Violet-crowned Hummingbird",
    "Violet-green Swallow",
    "Violet-headed Hummingbird",
    "Virginia Rail",
    "Virginia's Warbler",
    "Viridian Dacnis",
    "Vitelline Warbler",
    "Volcano Hummingbird",
    "Volcano Junco",
    "Wandering Tattler",
    "Warbling Vireo",
    "Wattled Jacana",
    "Waved Albatross",
    "Wedge-billed Woodcreeper",
    "Wedge-rumped Storm-Petrel",
    "Wedge-tailed Grass-Finch",
    "Wedge-tailed Sabrewing",
    "Wedge-tailed Shearwater",
    "West Indian Whistling-Duck",
    "West Indian Woodpecker",
    "West Mexican Chachalaca",
    "West Mexican Euphonia",
    "Western Bluebird",
    "Western Cattle-Egret",
    "Western Chat-Tanager",
    "Western Flycatcher",
    "Western Grebe",
    "Western Gull",
    "Western House-Martin",
    "Western Kingbird",
    "Western Marsh Harrier",
    "Western Meadowlark",
    "Western Olivaceous Flatbill",
    "Western Reef-Heron",
    "Western Sandpiper",
    "Western Screech-Owl",
    "Western Spindalis",
    "Western Tanager",
    "Western Wood-Pewee",
    "Western Woodhaunter",
    "Whimbrel",
    "Whiskered Auklet",
    "Whiskered Screech-Owl",
    "Whiskered Tern",
    "Whistling Heron",
    "Whistling Warbler",
    "White Cockatoo",
    "White Hawk",
    "White Ibis",
    "White Stork",
    "White Tern",
    "White Wagtail",
    "White-bellied Antbird",
    "White-bellied Chachalaca",
    "White-bellied Emerald",
    "White-bellied Mountain-gem",
    "White-bellied Wren",
    "White-breasted Nuthatch",
    "White-breasted Wood-Wren",
    "White-browed Gnatcatcher",
    "White-capped Albatross",
    "White-cheeked Pintail",
    "White-chinned Petrel",
    "White-chinned Swift",
    "White-chinned Thrush",
    "White-collared Manakin",
    "White-collared Swift",
    "White-crested Coquette",
    "White-crested Elaenia",
    "White-crowned Manakin",
    "White-crowned Parrot",
    "White-crowned Pigeon",
    "White-crowned Sparrow",
    "White-eared Conebill",
    "White-eared Ground-Sparrow",
    "White-eared Hummingbird",
    "White-eyed Thrush",
    "White-eyed Vireo",
    "White-faced Ground-Sparrow",
    "White-faced Ibis",
    "White-faced Quail-Dove",
    "White-faced Storm-Petrel",
    "White-faced Whistling-Duck",
    "White-flanked Antwren",
    "White-fronted Amazon",
    "White-fronted Nunbird",
    "White-fronted Quail-Dove",
    "White-fronted Swift",
    "White-fronted Tyrannulet",
    "White-headed Munia",
    "White-headed Woodpecker",
    "White-headed Wren",
    "White-lined Tanager",
    "White-lored Gnatcatcher",
    "White-naped Brushfinch",
    "White-naped Swift",
    "White-necked Crow",
    "White-necked Jacobin",
    "White-necked Petrel",
    "White-necked Puffbird",
    "White-ringed Flycatcher",
    "White-ruffed Manakin",
    "White-rumped Sandpiper",
    "White-shouldered Tanager",
    "White-striped Woodcreeper",
    "White-tailed Eagle",
    "White-tailed Emerald",
    "White-tailed Hawk",
    "White-tailed Hummingbird",
    "White-tailed Kite",
    "White-tailed Nightjar",
    "White-tailed Ptarmigan",
    "White-tailed Trogon",
    "White-tailed Tropicbird",
    "White-thighed Swallow",
    "White-throated Crake",
    "White-throated Flycatcher",
    "White-throated Jay",
    "White-throated Magpie-Jay",
    "White-throated Mountain-gem",
    "White-throated Needletail",
    "White-throated Shrike-Tanager",
    "White-throated Spadebill",
    "White-throated Sparrow",
    "White-throated Swift",
    "White-throated Thrush",
    "White-throated Towhee",
    "White-tipped Dove",
    "White-tipped Sicklebill",
    "White-vented Euphonia",
    "White-vented Plumeleteer",
    "White-whiskered Hermit",
    "White-whiskered Puffbird",
    "White-winged Becard",
    "White-winged Crossbill",
    "White-winged Dove",
    "White-winged Parakeet",
    "White-winged Scoter",
    "White-winged Swallow",
    "White-winged Tanager",
    "White-winged Tern",
    "White-winged Warbler",
    "Whooper Swan",
    "Whooping Crane",
    "Whooping Motmot",
    "Wild Turkey",
    "Willet",
    "Williamson's Sapsucker",
    "Willow Flycatcher",
    "Willow Ptarmigan",
    "Willow Warbler",
    "Wilson's Phalarope",
    "Wilson's Plover",
    "Wilson's Snipe",
    "Wilson's Storm-Petrel",
    "Wilson's Warbler",
    "Wine-throated Hummingbird",
    "Wing-banded Antbird",
    "Winter Wren",
    "Wood Duck",
    "Wood Sandpiper",
    "Wood Stork",
    "Wood Thrush",
    "Wood Warbler",
    "Woodhouse's Scrub-Jay",
    "Worm-eating Warbler",
    "Worthen's Sparrow",
    "Wrenthrush",
    "Wrentit",
    "Xantus's Hummingbird",
    "Yellow Bittern",
    "Yellow Grosbeak",
    "Yellow Oriole",
    "Yellow Rail",
    "Yellow Tyrannulet",
    "Yellow Warbler",
    "Yellow-backed Oriole",
    "Yellow-backed Tanager",
    "Yellow-bellied Elaenia",
    "Yellow-bellied Flycatcher",
    "Yellow-bellied Sapsucker",
    "Yellow-bellied Seedeater",
    "Yellow-bellied Siskin",
    "Yellow-bellied Tyrannulet",
    "Yellow-billed Amazon",
    "Yellow-billed Cacique",
    "Yellow-billed Cotinga",
    "Yellow-billed Cuckoo",
    "Yellow-billed Loon",
    "Yellow-billed Magpie",
    "Yellow-billed Tern",
    "Yellow-breasted Bunting",
    "Yellow-breasted Chat",
    "Yellow-breasted Crake",
    "Yellow-browed Bunting",
    "Yellow-browed Shrike-Vireo",
    "Yellow-browed Warbler",
    "Yellow-chevroned Parakeet",
    "Yellow-collared Chlorophonia",
    "Yellow-crowned Amazon",
    "Yellow-crowned Bishop",
    "Yellow-crowned Euphonia",
    "Yellow-crowned Night Heron",
    "Yellow-crowned Tyrannulet",
    "Yellow-eared Toucanet",
    "Yellow-eyed Junco",
    "Yellow-faced Grassquit",
    "Yellow-footed Gull",
    "Yellow-green Brushfinch",
    "Yellow-green Grosbeak",
    "Yellow-green Tyrannulet",
    "Yellow-green Vireo",
    "Yellow-headed Amazon",
    "Yellow-headed Blackbird",
    "Yellow-headed Caracara",
    "Yellow-headed Warbler",
    "Yellow-hooded Blackbird",
    "Yellow-legged Gull",
    "Yellow-lored Amazon",
    "Yellow-naped Amazon",
    "Yellow-olive Flatbill",
    "Yellow-rumped Cacique",
    "Yellow-rumped Warbler",
    "Yellow-shouldered Blackbird",
    "Yellow-shouldered Grassquit",
    "Yellow-tailed Oriole",
    "Yellow-thighed Brushfinch",
    "Yellow-throated Bunting",
    "Yellow-throated Chlorospingus",
    "Yellow-throated Euphonia",
    "Yellow-throated Nightingale-Thrush",
    "Yellow-throated Toucan",
    "Yellow-throated Vireo",
    "Yellow-throated Warbler",
    "Yellow-winged Cacique",
    "Yellow-winged Flatbill",
    "Yellow-winged Tanager",
    "Yellow-winged Vireo",
    "Yellowish Flycatcher",
    "Yellowish Pipit",
    "Yucatan Flycatcher",
    "Yucatan Gnatcatcher",
    "Yucatan Jay",
    "Yucatan Nightjar",
    "Yucatan Poorwill",
    "Yucatan Vireo",
    "Yucatan Woodpecker",
    "Yucatan Wren",
    "Zapata Rail",
    "Zapata Sparrow",
    "Zapata Wren",
    "Zeledon's Antbird",
    "Zenaida Dove",
    "Zino's Petrel",
    "Zone-tailed Hawk",
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    if (!croppedBlob) {
      setError('Please select a photo.');
      return;
    }
    if (!questId && !speciesId) {
      setError('Please select a species.');
      return;
    }
    if (croppedBlob.size > 5 * 1024 * 1024) {
      setError('File size must be 5MB or less.');
      return;
    }
    setUploading(true);
    try {
      // Upload full image
      const filePath = `${user?.id}/${questId ? `quest_${questId}` : `species_${speciesId}`}/${Date.now()}_cropped.jpg`;
      const { error: uploadError } = await supabase.storage.from('photos').upload(filePath, croppedBlob);
      if (uploadError) throw uploadError;
      // Generate and upload thumbnail
      const thumbBlob = await createThumbnail(croppedBlob, 360);
      const thumbPath = `${user?.id}/${questId ? `quest_${questId}` : `species_${speciesId}`}/${Date.now()}_thumb.jpg`;
      const { error: thumbError } = await supabase.storage.from('photos').upload(thumbPath, thumbBlob);
      if (thumbError) throw thumbError;
      let insertedPhotoId: string | null = null;
      if (questId) {
        // Store entry in quest_entries table
        await supabase.from('quest_entries').insert({
          user_id: user?.id,
          quest_id: questId,
          image_path: filePath,
          thumbnail_path: thumbPath,
        });
      } else {
        // Check if user already has a photo for this species
        await supabase
          .from('photos')
          .select('id')
          .eq('user_id', user?.id)
          .eq('species_id', speciesId);
        // const isFirst = !existingPhotos || existingPhotos.length === 0;
        // Store photo in photos table
        const { data: inserted, error: insertError } = await supabase.from('photos').insert({
          user_id: user?.id,
          species_id: speciesId,
          url: filePath,
          thumbnail_url: thumbPath,
        }).select('id').single();
        if (insertError) throw insertError;
        insertedPhotoId = inserted?.id;
        // If set as top, upsert into top_species
        if (setAsTop && insertedPhotoId) {
          await supabase.from('top_species').upsert([
            {
              user_id: user?.id,
              species_id: speciesId,
              photo_id: insertedPhotoId
            }
          ], { onConflict: 'user_id,species_id' });
        }
      }
      setFile(null);
      setCroppedBlob(null);
      setShowCropper(false);
      // setPrivacy removed
      setSpeciesId('');
      if (onUpload) onUpload();
    } catch (err: any) {
      setError(err.message || 'Upload failed');
    }
    setUploading(false);
  };

  return (
    <Paper elevation={0} sx={{ p: { xs: 1, sm: 2 }, width: '100%', background: 'transparent' }}>
      <Box component="form" onSubmit={handleSubmit} sx={{ width: '100%' }}>
        <Stack spacing={2}>
          {/* Species selection for normal uploads */}
          {!questId && (
            <Autocomplete
              options={HARDCODED_SPECIES}
              value={speciesId || null}
              onChange={(_, newValue) => {
                setSpeciesId(newValue || '');
              }}
              renderInput={(params) => (
                <TextField
                  {...params}
                  label="Species"
                  required
                  helperText="Type to search for a bird species"
                />
              )}
              filterOptions={(options, { inputValue }) => {
                const filtered = options.filter((option) =>
                  option.toLowerCase().includes(inputValue.toLowerCase())
                );
                return filtered.slice(0, 50); // Limit to 50 results for performance
              }}
              noOptionsText="No species found"
              clearOnEscape
              selectOnFocus
              handleHomeEndKeys
            />
          )}
          <FormControl fullWidth required>
            <Button
              variant="outlined"
              component="label"
              sx={{ width: '100%', justifyContent: 'flex-start', textTransform: 'none' }}
              disabled={uploading}
            >
              {file ? file.name : 'Choose Photo'}
              <input
                type="file"
                accept="image/*"
                hidden
                onChange={e => {
                  const f = e.target.files?.[0] || null;
                  setFile(f);
                  setCroppedBlob(null);
                  if (f) setShowCropper(true);
                }}
                required
              />
            </Button>
            <FormHelperText>Select a photo to upload (max 5MB)</FormHelperText>
          </FormControl>
          {showCropper && file && (
            <Box sx={{ my: 2, mx: 'auto', width: 1, maxWidth: 600 }}>
              <ImageCropper
                file={file}
                onCropped={blob => {
                  setCroppedBlob(blob);
                  setShowCropper(false);
                }}
                onCancel={() => {
                  setShowCropper(false);
                  setFile(null);
                  setCroppedBlob(null);
                }}
              />
            </Box>
          )}
          {/* Privacy selection removed */}
          {/* Set as top photo checkbox (only for non-quest uploads) */}
          {!questId && (
            <FormControlLabel
              control={
                <Checkbox
                  checked={setAsTop}
                  onChange={e => setSetAsTop(e.target.checked)}
                  color="primary"
                  disabled={uploading}
                />
              }
              label="Set as top photo for this species"
              sx={{ mb: 1 }}
            />
          )}
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Button type="submit" variant="contained" color="primary" disabled={uploading} sx={{ minWidth: 120 }}>
              {uploading ? <CircularProgress size={20} /> : 'Upload'}
            </Button>
            {onCancel && (
              <Button onClick={onCancel} disabled={uploading} variant="outlined">Cancel</Button>
            )}
            {error && <FormHelperText error>{error}</FormHelperText>}
          </Box>
        </Stack>
      </Box>
    </Paper>
  );
};

export default PhotoUpload;
